### ISSUE TITLE
safranashereen: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by safranashereen** [ChemixLab/chemix_lab#1]
I have pretty good interested to join this project to help on the back-end coding on PHP. I have one of the co-founder of Chemix Lab.<p><br><blockquote>This issue was created by @safranashereen via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by nifrasismail** [comment]
Great we are need to creating chmix collaborate page fir collecting different kind of reactions and we generalize our project. I contact you in uni
